// Generated by gencpp from file planner/agent_status.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_AGENT_STATUS_H
#define PLANNER_MESSAGE_AGENT_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace planner
{
template <class ContainerAllocator>
struct agent_status_
{
  typedef agent_status_<ContainerAllocator> Type;

  agent_status_()
    : header()
    , curr_pos()  {
    }
  agent_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , curr_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _curr_pos_type;
  _curr_pos_type curr_pos;





  typedef boost::shared_ptr< ::planner::agent_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::agent_status_<ContainerAllocator> const> ConstPtr;

}; // struct agent_status_

typedef ::planner::agent_status_<std::allocator<void> > agent_status;

typedef boost::shared_ptr< ::planner::agent_status > agent_statusPtr;
typedef boost::shared_ptr< ::planner::agent_status const> agent_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::agent_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::agent_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'planner': ['/home/siddharth/multi_robo_plan/src/planner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner::agent_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::agent_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::agent_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::agent_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::agent_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::agent_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::agent_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18a610e395f7e023adac4db0dcbdf859";
  }

  static const char* value(const ::planner::agent_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18a610e395f7e023ULL;
  static const uint64_t static_value2 = 0xadac4db0dcbdf859ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::agent_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/agent_status";
  }

  static const char* value(const ::planner::agent_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::agent_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] curr_pos\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::planner::agent_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::agent_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.curr_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agent_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::agent_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::agent_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "curr_pos[]" << std::endl;
    for (size_t i = 0; i < v.curr_pos.size(); ++i)
    {
      s << indent << "  curr_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.curr_pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_AGENT_STATUS_H
