// Generated by gencpp from file planner/goal_update.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_GOAL_UPDATE_H
#define PLANNER_MESSAGE_GOAL_UPDATE_H

#include <ros/service_traits.h>


#include <planner/goal_updateRequest.h>
#include <planner/goal_updateResponse.h>


namespace planner
{

struct goal_update
{

typedef goal_updateRequest Request;
typedef goal_updateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goal_update
} // namespace planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner::goal_update > {
  static const char* value()
  {
    return "436099e14cbdae6055989aead131b550";
  }

  static const char* value(const ::planner::goal_update&) { return value(); }
};

template<>
struct DataType< ::planner::goal_update > {
  static const char* value()
  {
    return "planner/goal_update";
  }

  static const char* value(const ::planner::goal_update&) { return value(); }
};


// service_traits::MD5Sum< ::planner::goal_updateRequest> should match 
// service_traits::MD5Sum< ::planner::goal_update > 
template<>
struct MD5Sum< ::planner::goal_updateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner::goal_update >::value();
  }
  static const char* value(const ::planner::goal_updateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::goal_updateRequest> should match 
// service_traits::DataType< ::planner::goal_update > 
template<>
struct DataType< ::planner::goal_updateRequest>
{
  static const char* value()
  {
    return DataType< ::planner::goal_update >::value();
  }
  static const char* value(const ::planner::goal_updateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner::goal_updateResponse> should match 
// service_traits::MD5Sum< ::planner::goal_update > 
template<>
struct MD5Sum< ::planner::goal_updateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner::goal_update >::value();
  }
  static const char* value(const ::planner::goal_updateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::goal_updateResponse> should match 
// service_traits::DataType< ::planner::goal_update > 
template<>
struct DataType< ::planner::goal_updateResponse>
{
  static const char* value()
  {
    return DataType< ::planner::goal_update >::value();
  }
  static const char* value(const ::planner::goal_updateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MESSAGE_GOAL_UPDATE_H
