// Generated by gencpp from file planner/goal_updateResponse.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_GOAL_UPDATERESPONSE_H
#define PLANNER_MESSAGE_GOAL_UPDATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct goal_updateResponse_
{
  typedef goal_updateResponse_<ContainerAllocator> Type;

  goal_updateResponse_()
    : run()  {
    }
  goal_updateResponse_(const ContainerAllocator& _alloc)
    : run(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _run_type;
  _run_type run;





  typedef boost::shared_ptr< ::planner::goal_updateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::goal_updateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goal_updateResponse_

typedef ::planner::goal_updateResponse_<std::allocator<void> > goal_updateResponse;

typedef boost::shared_ptr< ::planner::goal_updateResponse > goal_updateResponsePtr;
typedef boost::shared_ptr< ::planner::goal_updateResponse const> goal_updateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::goal_updateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::goal_updateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner': ['/home/siddharth/multi_robo_plan/src/planner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner::goal_updateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::goal_updateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::goal_updateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::goal_updateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::goal_updateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::goal_updateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::goal_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc810bfd9bba1f4be290057b4ee1f72d";
  }

  static const char* value(const ::planner::goal_updateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc810bfd9bba1f4bULL;
  static const uint64_t static_value2 = 0xe290057b4ee1f72dULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::goal_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/goal_updateResponse";
  }

  static const char* value(const ::planner::goal_updateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::goal_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string run\n\
\n\
";
  }

  static const char* value(const ::planner::goal_updateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::goal_updateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goal_updateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::goal_updateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::goal_updateResponse_<ContainerAllocator>& v)
  {
    s << indent << "run: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_GOAL_UPDATERESPONSE_H
