// Generated by gencpp from file planner/planRequest.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_PLANREQUEST_H
#define PLANNER_MESSAGE_PLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct planRequest_
{
  typedef planRequest_<ContainerAllocator> Type;

  planRequest_()
    : goal()
    , start()
    , id()  {
    }
  planRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , start(_alloc)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _goal_type;
  _goal_type goal;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _start_type;
  _start_type start;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::planner::planRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::planRequest_<ContainerAllocator> const> ConstPtr;

}; // struct planRequest_

typedef ::planner::planRequest_<std::allocator<void> > planRequest;

typedef boost::shared_ptr< ::planner::planRequest > planRequestPtr;
typedef boost::shared_ptr< ::planner::planRequest const> planRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::planRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::planRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner': ['/home/siddharth/multi_robo_plan/src/planner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner::planRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::planRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::planRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::planRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::planRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::planRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7da21cd8786103d5266373aa7388bd0";
  }

  static const char* value(const ::planner::planRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7da21cd8786103dULL;
  static const uint64_t static_value2 = 0x5266373aa7388bd0ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/planRequest";
  }

  static const char* value(const ::planner::planRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::planRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] goal\n\
float64[] start\n\
string id\n\
";
  }

  static const char* value(const ::planner::planRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::planRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.start);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::planRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::planRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.goal[i]);
    }
    s << indent << "start[]" << std::endl;
    for (size_t i = 0; i < v.start.size(); ++i)
    {
      s << indent << "  start[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.start[i]);
    }
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_PLANREQUEST_H
