// Generated by gencpp from file planner/planResponse.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_PLANRESPONSE_H
#define PLANNER_MESSAGE_PLANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct planResponse_
{
  typedef planResponse_<ContainerAllocator> Type;

  planResponse_()
    : plan_x()
    , plan_y()  {
    }
  planResponse_(const ContainerAllocator& _alloc)
    : plan_x(_alloc)
    , plan_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _plan_x_type;
  _plan_x_type plan_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _plan_y_type;
  _plan_y_type plan_y;





  typedef boost::shared_ptr< ::planner::planResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::planResponse_<ContainerAllocator> const> ConstPtr;

}; // struct planResponse_

typedef ::planner::planResponse_<std::allocator<void> > planResponse;

typedef boost::shared_ptr< ::planner::planResponse > planResponsePtr;
typedef boost::shared_ptr< ::planner::planResponse const> planResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::planResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::planResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner': ['/home/siddharth/multi_robo_plan/src/planner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner::planResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::planResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::planResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::planResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::planResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::planResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::planResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a1c16cdfeb33748b323312f10aaa4b7";
  }

  static const char* value(const ::planner::planResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a1c16cdfeb33748ULL;
  static const uint64_t static_value2 = 0xb323312f10aaa4b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::planResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/planResponse";
  }

  static const char* value(const ::planner::planResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::planResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] plan_x\n\
float64[] plan_y\n\
\n\
";
  }

  static const char* value(const ::planner::planResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::planResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_x);
      stream.next(m.plan_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::planResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::planResponse_<ContainerAllocator>& v)
  {
    s << indent << "plan_x[]" << std::endl;
    for (size_t i = 0; i < v.plan_x.size(); ++i)
    {
      s << indent << "  plan_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.plan_x[i]);
    }
    s << indent << "plan_y[]" << std::endl;
    for (size_t i = 0; i < v.plan_y.size(); ++i)
    {
      s << indent << "  plan_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.plan_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_PLANRESPONSE_H
