// Generated by gencpp from file planner/plan.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_PLAN_H
#define PLANNER_MESSAGE_PLAN_H

#include <ros/service_traits.h>


#include <planner/planRequest.h>
#include <planner/planResponse.h>


namespace planner
{

struct plan
{

typedef planRequest Request;
typedef planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plan
} // namespace planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner::plan > {
  static const char* value()
  {
    return "27f79911e87bcca9dad2a28a074d44b4";
  }

  static const char* value(const ::planner::plan&) { return value(); }
};

template<>
struct DataType< ::planner::plan > {
  static const char* value()
  {
    return "planner/plan";
  }

  static const char* value(const ::planner::plan&) { return value(); }
};


// service_traits::MD5Sum< ::planner::planRequest> should match 
// service_traits::MD5Sum< ::planner::plan > 
template<>
struct MD5Sum< ::planner::planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner::plan >::value();
  }
  static const char* value(const ::planner::planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::planRequest> should match 
// service_traits::DataType< ::planner::plan > 
template<>
struct DataType< ::planner::planRequest>
{
  static const char* value()
  {
    return DataType< ::planner::plan >::value();
  }
  static const char* value(const ::planner::planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner::planResponse> should match 
// service_traits::MD5Sum< ::planner::plan > 
template<>
struct MD5Sum< ::planner::planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner::plan >::value();
  }
  static const char* value(const ::planner::planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::planResponse> should match 
// service_traits::DataType< ::planner::plan > 
template<>
struct DataType< ::planner::planResponse>
{
  static const char* value()
  {
    return DataType< ::planner::plan >::value();
  }
  static const char* value(const ::planner::planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MESSAGE_PLAN_H
